motd:
  enabled: true
  motds:
    - |-
      &r                       &6&lFishy&f&lMinecraft &a[1.8]
      &r                       &c&lSKYBLOCK&r &7| &6&lJOIN NOW！

# This is the list of message shown when hovering over the player count.
# Only works on Bukkit (Requires ProtocolLib)
sample:
  enabled: true
  # Placeholders: %onlineplayers% %maxplayers%
  samples:
    - |-
      Online: %onlineplayers%/%maxplayers%

protocol:
  enabled: true
  name: "NullCockX 1.8"

maxplayers:
  enabled: false
  maxplayers: 1400
  justonemore: true
fakeplayers:
  enabled: false
  amount: 3

  # "STATIC": Adds the value of fakeplayers to the amount of players online.
  # "RANDOM": Adds a random amount of players between 1 and the fakeplayers value.
  # "DIVISION": Adds the amount of players online divided by the fakeplayers value.
  mode: "DIVISION"
